version: 2.1
jobs:
  build:
  deploy:
    machine:
      enabled: true
    steps:          
      - run:
          name: SSH into EC2
          command: |
            ssh -i $SSH_KEY -p $SSH_PORT $SSH_USER@$SSH_HOST
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci-project-setup

