version: 2.1
jobs:
  build:
    machine:
      enabled: true
    steps:
      - run:
          name: Placeholder Build Step
          command: echo "Running the build job"
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - ed:fa:5e:7f:d8:46:33:21:ea:70:dd:1a:de:01:31:58     
      - run:
          name: SSH into EC2
          command: |
            ssh -i  ed:fa:5e:7f:d8:46:33:21:ea:70:dd:1a:de:01:31:58 -p $SSH_PORT $SSH_USER@$SSH_HOST 

